### ISSUE TITLE
Where can I download data of town? 

### ISSUE THREAD

**Issue by leonlee723** [ZATiTech/open_planner#1]
Hi Hatem Darweesh. I watch your youtube video and read your code. That's a great job. I'm trying to reimplement those codes in my environment. But I don't find the data(lanelet2 and point cloud) of town that you mention under autoware_universe_sample_data  in the video. Do you give me a hint about those data? Thanks.

**Comment by hatem-darweesh** [comment]
@leonlee723 
you can download them from here 
https://drive.google.com/drive/u/1/folders/1Or0CMS08AW8XvJtzzR8TfhqdY9MMUBpS

**Comment by leonlee723** [comment]
Thank you very much. Have a good weekend!
