### ISSUE TITLE
Package open_planner build failed with "uninitialized [-Werror=uninitialized]" error

### ISSUE THREAD

**Issue by Gowtham-Raj-M** [ZATiTech/open_planner#10]
Hi @hatem-darweesh,
I followed the process explained in the "CARLA - Autoware universe Tutorial 1" video for setting up CARLA and Autoware universe, but the Colon build failed in the open_planner package with an "uninitialized [-Werror=uninitialized]" error. Could you please help in fixing the issue.

Issue:
-- stderr: open_planner                                                                                                                                                    
/home/ubuntu/Documents/carla-autoware-universe/autoware.universe.openplanner/src/universe/external/open_planner/op_lib/src/mapping/opendrive/geometry/LaneUtils.cpp: In function ‘opendrive::geometry::BoostPolygon opendrive::geometry::fromLane(const opendrive::Lane&, double)’:
/home/ubuntu/Documents/carla-autoware-universe/autoware.universe.openplanner/src/universe/external/open_planner/op_lib/src/mapping/opendrive/geometry/LaneUtils.cpp:56:16: error: ‘orthogonalDirection.boost::geometry::model::d2::point_xy<double, boost::geometry::cs::cartesian>::<unnamed>.boost::geometry::model::point<double, 2, boost::geometry::cs::cartesian>::m_values[0]’ is used uninitialized [-Werror=uninitialized]
   56 |   Boost2dPoint orthogonalDirection;
      |                ^~~~~~~~~~~~~~~~~~~
/home/ubuntu/Documents/carla-autoware-universe/autoware.universe.openplanner/src/universe/external/open_planner/op_lib/src/mapping/opendrive/geometry/LaneUtils.cpp:56:16: error: ‘orthogonalDirection.boost::geometry::model::d2::point_xy<double, boost::geometry::cs::cartesian>::<unnamed>.boost::geometry::model::point<double, 2, boost::geometry::cs::cartesian>::m_values[1]’ is used uninitialized [-Werror=uninitialized]
cc1plus: all warnings being treated as errors
gmake[2]: *** [CMakeFiles/openplanner.dir/build.make:356: CMakeFiles/openplanner.dir/src/mapping/opendrive/geometry/LaneUtils.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:137: CMakeFiles/openplanner.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< open_planner [31.3s, exited with code 2]
Aborted  <<< tier4_traffic_light_rviz_plugin [21.9s]                                                                                                                                                      
Aborted  <<< lanelet2_map_preprocessor [32.1s]                                                                                                                                                             
Aborted  <<< tier4_vehicle_rviz_plugin [16.8s]                                                                                                                                                              
Aborted  <<< radar_tracks_msgs_converter [47.0s]                                                                                                                                                                  
Aborted  <<< radar_fusion_to_detected_object [47.7s]                                                                                                                                                        
Aborted  <<< radar_static_pointcloud_filter [51.3s]                                                                                                     
Aborted  <<< tier4_control_rviz_plugin [59.8s]                                           

Summary: 226 packages finished [1min 29s]
  1 package failed: open_planner
  7 packages aborted: lanelet2_map_preprocessor radar_fusion_to_detected_object radar_static_pointcloud_filter radar_tracks_msgs_converter tier4_control_rviz_plugin tier4_traffic_light_rviz_plugin tier4_vehicle_rviz_plugin
  1 package had stderr output: open_planner
  22 packages not processed

**Comment by thiruppathik-tw** [comment]
This is happening for me as well

**Comment by thiruppathik-tw** [comment]
@Gowtham-Raj-M how did you solved this
