### ISSUE TITLE
In the latest universe and carla co-simulation, the ego vehicle failed to locate successfully

### ISSUE THREAD

**Issue by wohu1104** [ZATiTech/open_planner#12]
Hi @hatem-darweesh ,
Thank you for the great work.

I followed the three tutorials below to recreate the universe and carla co-simulation

[https://github.com/ZATiTech/open_planner/tree/humble/op_carla_bridge](https://github.com/ZATiTech/open_planner/tree/humble/op_carla_bridge)

[https://github.com/hatem-darweesh/op_agent/tree/ros2-humble](https://github.com/hatem-darweesh/op_agent/tree/ros2-humble)

[https://github.com/hatem-darweesh/op_bridge/tree/ros2-humble](https://github.com/hatem-darweesh/op_bridge/tree/ros2-humble)

My environment is

- Ubuntu22.04
- ROS2 humble
- Carla 0.9.15

I think I have completely followed all the steps of the tutorial, but as shown in the figure, the ego vehicle has been at the origin coordinates, and there are errors on the command line as follows, I am not sure whether these errors have an impact on the system.

```shell
[system.service_log_checker]: /localization/initialize: status code 4 'NDT align server failed.' (/default_ad_api/node/localization) (set_error() at /home/dep/project/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:83)
[service_log_checker-5] [ERROR 1704596860.962163046] [system.service_log_checker]: /api/localization/initialize: status code 4 'NDT align server failed.' (/default_ad_api/node/localization) (set_error() at /home/dep/project/autoware/src/universe/autoware.universe/common/component_interface_tools/src/service_log_checker.cpp:83)

``` 

```shell
[perception.occupancy_grid_map.occupancy_grid_map_node]: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees. (onPointcloudWithObstacleAndRaw() at /home/dep/project/autoware/src/universe/autoware.universe/perception/probabilistic_occupancy_grid_map/src/pointcloud_based_occupancy_grid_map/pointcloud_based_occupancy_grid_map_node.cpp:179)
```

```shell
[system.system_error_monitor]: input data is timeout (onTimer() at /home/dep/project/autoware/src/universe/autoware.universe/system/system_error_monitor/src/system_error_monitor_core.cpp:447)
```

![image](https://github.com/ZATiTech/open_planner/assets/35565391/e038eae1-3b41-4a26-b720-0fa1f88f76d1)

I'm very much looking forward to your reply. Thanks.

**Comment by hatem-darweesh** [comment]
I found several issues related to the Autoware requirements such as: 
- Sensing topics frequency 
- LIDAR data format and driver output. 
- Which version from Autoware is stable to work with the bridge. 

I am trying to fix these issues now. 
Will update the read me and the source code soon. 
Thanks

**Comment by hatem-darweesh** [comment]
Kindly check the updated instruction:
https://github.com/ZATiTech/open_planner/blob/humble/op_carla_bridge/README.md

autoware.universe release/2023.10

**Comment by wohu1104** [comment]
@hatem-darweesh 

Thanks again for your prompt reply.

According to the latest guidance document, it is indeed a big improvement from before.

However, I've encountered a new problem as shown below, it seems that the position of the ego vehicle in Carla does not match the position in RVIZ? Resulting in the planned path not working correctly.

![2024-01-09_11-01_1](https://github.com/ZATiTech/open_planner/assets/35565391/f74193f1-6216-46c2-b7a3-3da133026a17)

Can you help analyze what might be incorrectly configured to cause this issue?

Maybe need to change where the ego vehicle is generated in carla?

Best wishes.

**Comment by wohu1104** [comment]
Once I changed the spawn location of the ego vehicle and restarted the script it went back to normal, probably due to my historical operations.  

Thank you for your great work again.

**Comment by ZhouTao415** [comment]
Thank you for the great work.
I have also the same problem and solve the problem with you advice. 
When i run the 
```bash
./run_exploration_mode_ros2.sh 
```
the Localization is right, and the image can be showed.

But when i run 
```bash
./run_route_scenarios_ros2.sh 
```
the Localization is not right.  You can see the followed Scrennshot.

![Screenshot from 2024-01-22 10-55-47](https://github.com/ZATiTech/open_planner/assets/85726512/8cc5c3da-580d-4fee-b3b0-287a2df0fea4)

I try to solve the problem but it's still not working. How can i solve this problems. Thanks

**Comment by TianYifan-Vincent** [comment]
@wohu1104 Sorry to bother you, I met the same question: The ego vehicle was at the origin coordinates. And I followed latest guidance document but still failed, could you give me some detailed suggestions?

**Comment by wohu1104** [comment]
> @wohu1104 Sorry to bother you, I met the same question: The ego vehicle was at the origin coordinates. And I followed latest guidance document but still failed, could you give me some detailed suggestions?

@TianYifan-Vincent 
1. Is the LiDAR point cloud normal?

2. Try a new starting coordinate?

**Comment by TianYifan-Vincent** [comment]
> > @wohu1104 Sorry to bother you, I met the same question: The ego vehicle was at the origin coordinates. And I followed latest guidance document but still failed, could you give me some detailed suggestions?
> 
> @TianYifan-Vincent
> 
> 1. Is the LiDAR point cloud normal?
> 2. Try a new starting coordinate?

Thank you for your suggestions. As the figure shows, my Global status shows Error: Frame[map] does not exist. I tried a new starting coordinate and didn't work. I think there might be a problem bridging carla and autoware's positioning. 
Looking back at the steps I followed the material, there are two parts of it that I think may have confused me.
First, Lidar Driver (tier4/universe and awf/main) branch, which is appropriate, though I have both tried.
Second, copy the files (sensor_kit_calibration.yaml, sensors.calibration.yaml) from folder "autoware/src/universe/external/open_planner/op_carla_bridge/carla_sensor_kit_launch/carla_sensor_kit_description/config" to "autoware/src/param/autoware_individual_params/individual_params/config/default/carla_sensor_kit".(Maybe a little different from the path of the tutorial.) And then rebuild the autoware. 
Besides, do i need modify any other file like autoware.launch.xml, because in some blogs, add some `<arg name="launch_carla_interface">` or change true to false in launch_sensing_driver and use_sim_time, etc.
I'm a beginner student so I'm not sure if what I mentioned above will make a difference to bridge, please correct me, thanks a lot for taking your time! 
![7aafc7f00ccf4bd21efa98e3513ebcb](https://github.com/ZATiTech/open_planner/assets/72920835/7b4f5fab-5abf-44ac-82ba-0af008537733)

**Comment by wohu1104** [comment]
@TianYifan-Vincent 

First, you look at the command line to start autoware is there no error print? It looks like there was already a problem when starting autoware(rviz).

Second, confirm that the autoware environment is normal. Can autoware work normally if autoware is started separately without the co-simulation with carla?

**Comment by TianYifan-Vincent** [comment]
@wohu1104
Thank you for your help. Autoware can work normally without carla, but using “2D Pose Estimate” to specify a starting point doesn't work. And when run `./../op_carla/op_bridge/op_scripts/run_exploration_mode_ros2.sh` , there are two log errors in the command line I need to pay attention to.
First, The GNSS pose has not arrived.
```
[ERROR] [system.service_log_checker]: /localization/initialize: status code 3 'The GNSS pose has not arrived.' (/localization/util/pose_initializer_node)
[ERROR] [system.service_log_checker]: /localization/initialize: status code 3 'The GNSS pose has not arrived.' (/default_ad_api/node/localization)
```
Second, Cannot find the reference position for map update. Please check if the EKF odometry is provided to NDT.
```
[ERROR] [localization.pose_estimator.ndt_scan_matcher]: Cannot find the reference position for map update. Please check if the EKF odometry is provided to NDT.
```
![rviz](https://github.com/ZATiTech/open_planner/assets/72920835/afec8455-5a49-4d09-b92d-c645f291e9dd)

**Comment by wohu1104** [comment]
@TianYifan-Vincent 
 Autoware can work normally without carla, but using “2D Pose Estimate” to specify a starting point doesn't work. ——This phenomenon indicates that Autoware is not working properly.It is recommended that you check the Autoware environment.
