### ISSUE TITLE
Doubts about file modification in the final step of the humble tutorial

### ISSUE THREAD

**Issue by tk-menot** [ZATiTech/open_planner#18]
Hi @hatem-darweesh ,
Thank you for the great work. I have followed humble tutorials to implement co-simulation. My environment is Ubuntu22.04+ROS2 humble+autoware release/2023.10.

In the galactic version, we need to modify four files, gnss.launch.xml、autoware.launch.xml、sensor_kit_calibration.yaml、sensors.calibration.yaml. However, in humble version, the tutorials do not mention the first two. I am puzzled whether the first two files should be modified.

Also, in the galactic version,  sensor_kit_calibration.yaml、sensors.calibration.yaml  is in "src/sensor_kit/sample_sensor_kit_launch/sample_sensor_kit_description/config". But in humble version,  the tutorials mention "src/param/autoware_indicidual_params/carla_sensor_kit". Where should these two files be placed?

Besides, may I ask if the final step of the tutorial is to compile autoware? Is it only necessary to compile newly added packages, or do I need to recompile all packages?

I'm looking forward to your reply. Thank you.
I

**Comment by hatem-darweesh** [comment]
Hi @tk-menot 

- Autoware team changed the way GNSS is handled in the Localization and mapping. that is why we don't need to change the those .xml files. 
- same for the sensor kit calibration. 
- the sensor kit configuration should be placed in two places: (default place, and src/param/autoware_individual_params/) there were a spilling mistake here. this is the place in the original repo: https://github.com/autowarefoundation/autoware_individual_params/tree/main/individual_params/config/default

**Comment by tk-menot** [comment]
I understand, thank you for your reply
