### ISSUE TITLE
Issue with the carla egg version in .bashrc

### ISSUE THREAD

**Issue by fengyeying** [ZATiTech/open_planner#5]
thank you for this excellent work. My python version is 3.8, and I installed the Carla lib by pip. So should I delete the part of egg file in .bashrc, or just modified it to the path of py3.7 lib in the Carla folder?
I tried to delete this part, but the RecognitionResultOnImage panel has no Image. And if I add it in .bashrc , the vehicle cannot engage, and the state will be "PLANNING" all the time.

**Comment by hatem-darweesh** [comment]
I wish I had a concrete answer. 
Soon I will modify the bridge to work with Autoware.Univers humble version. hope that will solve all these issues.
