### ISSUE TITLE
Issue with non stop planning

### ISSUE THREAD

**Issue by chizro0** [ZATiTech/open_planner#6]
Hi, I built the repo provided by zatitech and using ros galactic and CARLA_0.9.13. I faced an issue after setting the goal pose. It seemed like the planning stage was never finished, like the image below:
![image](https://user-images.githubusercontent.com/94829693/210166692-bfc7061f-ceaa-4617-b404-fbf7d716c514.png)

Here I collected the info message after setting the goal pose:

> [rviz2-81] [INFO] [1672564514.846074712] [rviz2]: Setting goal pose: Frame:map, Position(89.1819, -298.359, 0), Orientation(0, 0, -0.776278, 0.630391) = Angle: -1.77748
> ...
> [component_container-43] [pcl::KdTreeFLANN::setInputCloud] Cannot create a KDTree with an empty input cloud!
> [component_container-67] [WARN] [1672566460.474563839] [control.vehicle_cmd_gate]: external_emergency_stop_heartbeat_received_time_ is false
> ...
> [routing_adaptor-71] [INFO] [1672564515.555615187] [default_ad_api.helpers.routing_adaptor]: client call: /api/routing/set_route_points
> [component_container_mt-68] [INFO] [1672564515.571785388] [default_ad_api.node.routing]: server call: /api/routing/set_route_points
> [component_container_mt-68] [INFO] [1672564515.572378777] [default_ad_api.node.routing]: client call: /planning/mission_planning/set_route_points
> [mission_planner-57] [INFO] [1672564515.572609473] [planning.mission_planning.mission_planner]: server call: /planning/mission_planning/set_route_points
> [mission_planner-57] [INFO] [1672564515.572776570] [planning.mission_planning.mission_planner]: start planning route with check points: 
> [mission_planner-57] x: 88.6273 y: -226.89
> [mission_planner-57] x: 89.1819 y: -298.359
> [mission_planner-57] 
> [mission_planner-57] [INFO] [1672564515.574225843] [planning.mission_planning.mission_planner]: server exit: /planning/mission_planning/set_route_points
> [component_container_mt-68] [INFO] [1672564515.575723615] [default_ad_api.node.routing]: client exit: /planning/mission_planning/set_route_points
> [component_container_mt-68] [INFO] [1672564515.575789014] [default_ad_api.node.routing]: server exit: /api/routing/set_route_points
> [routing_adaptor-71] [INFO] [1672564515.575963211] [default_ad_api.helpers.routing_adaptor]: client exit: /api/routing/set_route_points
> ...
> [component_container-67] [INFO] [1672564515.717378395] [control.trajectory_follower.lane_departure_checker_node]: waiting for reference_trajectory msg...
> ...
> [component_container_mt-62] [INFO] [1672564516.120749033] [planning.scenario_planning.lane_driving.behavior_planning.behavior_velocity_planner]: register task: module = occlusion_spot, id = 0
> ...
> [component_container_mt-64] [WARN] [1672564519.357707573] [util]: [Avoidance] EB:  OSQP solution status: OSQP_SOLVED_INACCURATE
> ...
> [component_container_mt-4] [ERROR] [1672564520.413235058] [system.system_monitor.hdd_monitor]: socket connect error. Connection refused
> [component_container_mt-4] [ERROR] [1672564520.413635950] [system.system_monitor.hdd_monitor]: Failed to unmount device : overlay
> ...
> [component_container_mt-74] [WARN] [1672564525.197928527] [autoware_api.external.vehicle_status]: The turn_indicators topic is not subscribed
> [component_container-67] [INFO] [1672564526.282680686] [control.vehicle_cmd_gate]: waiting topics...
> ...
> [system_error_monitor-21] [ERROR] [1672564526.438668904] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring]: [Single Point Fault]: Error
> [system_error_monitor-21] [ERROR] [1672564526.438707304] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring/topic_status/topic_state_monitor_control_command_control_cmd: control_topic_status]: [Single Point Fault]: Error
> [system_error_monitor-21] [ERROR] [1672564526.438718603] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring/topic_status/topic_state_monitor_trajectory_follower_control_cmd: control_topic_status]: [Single Point Fault]: OK
> ...
> 

And I tried to engage, it failed for the planning not completed:

> [rviz2-81] [INFO] [1672564619.747932159] [rviz2]: client request
> [component_container_mt-74] [INFO] [1672564619.749558929] [autoware_api.external.engage]: service request
> [component_container_mt-74] [INFO] [1672564619.749622128] [autoware_api.external.engage]: service response
> [rviz2-81] [INFO] [1672564619.752159082] [rviz2]: Status: 4, It is not ready to engage.
> ...
> [component_container-67] [INFO] [1672564620.317907835] [control.vehicle_cmd_gate]: waiting topics...
> [system_error_monitor-21] [ERROR] [1672564620.499165620] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring]: [Single Point Fault]: Error
> [system_error_monitor-21] [ERROR] [1672564620.499829208] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring/topic_status/topic_state_monitor_control_command_control_cmd: control_topic_status]: [Single Point Fault]: Error
> [system_error_monitor-21] [ERROR] [1672564620.499874407] [system_error_monitor /autoware/control/autonomous_driving/node_alive_monitoring/topic_status/topic_state_monitor_trajectory_follower_control_cmd: control_topic_status]: [Single Point Fault]: OK

Is there any clue how to solve this problem?  
I appreciate all the help. Thanks in advance.

**Comment by hatem-darweesh** [comment]
It is a problem with autoware.universe not the bridge 
check also issues: https://github.com/hatem-darweesh/op_bridge/issues
