### ISSUE TITLE
Issues with network connection lost

### ISSUE THREAD

**Issue by leeseho** [ZATiTech/open_planner#7]
Hi, I'm trying to setup carla-autoware integration environment.

but, There seem to be an issue with connection between carla and autoware. 
In the video I upload, you can see that network connection lost when I launch autoware. 
also there was an issue with ROS when I first launched autoware universe. (but i don't have any log about the error).

The weird thing is that there's no problem in another PC although I installed autoware in the same way.

Thanks for any help.

environment:
CPU : i7 10700F
GPU : RTX 3070 Ti
RAM : 32GB
OS : Ubuntu 20.04 LTS
ROS version : Galactic
Python version : 3.8.10

[video](https://drive.google.com/file/d/1OxM8F3MbhnXkAMDkBjQWNnvNuxOvjFVx/view?usp=sharing)
[log](https://drive.google.com/file/d/1irkFvOw30aYONjIeWFn0E0dFdYzayjVR/view?usp=sharing)

**Comment by hatem-darweesh** [comment]
Sorry, never seen such an error. 
try to check if autoware.universe work without the bridge first. try to planning simulator (first tutorial for autoware).

**Comment by leeseho** [comment]
Thanks for a comment. It was a matter of hub setting,
