### ISSUE TITLE
OpenPlanner bridge not building

### ISSUE THREAD

**Issue by MarioAlmelaUMH** [ZATiTech/open_planner#9]
--------------------------------------------
OS: Ubuntu 20 (Focal Fossa)
ROS: ROS 2 Galactic
CARLA: 0.9.13
Autoware: Universe (ROS 2 Galactic branch)
GCC: 9.4.0
CMake: 3.25.2
---------------------------------------------

Hello, I’m trying to use this bridge to connect CARLA 0.9.13 with Autoware (ROS Galactic version). Whenever I try to build the bridge, I get this error when trying to buid the package ‘traffic light selector’: decltype cannot resolve address of overloaded function

![console](https://user-images.githubusercontent.com/119304913/227483983-6800c722-5bf1-4203-8fab-ac6c2764f1fd.png)

I’ve tried to add the parameter -DCMAKE_CXX_STANDARD=17, as I saw on the internet, but the error prevails. I’ve also tried to build every other package except ‘traffic light selector’ using –packages-skip, but then other packages start breaking:

![error2](https://user-images.githubusercontent.com/119304913/227484283-e8b0744a-0de9-405e-b1bf-c07f1cfc800a.png)

Is something wrong with rclcpp? I have two ROS distros installed (foxy and galactic), is that the reason?

Thank you in advance.

**Comment by hatem-darweesh** [comment]
I don't know ! 
How this is related to the bridge ?!
can you build autoware.universe without the bridge ?

**Comment by MarioAlmelaUMH** [comment]
I can. I have the ROS Galactic version of Autoware already installed and working. However, when I use the command **colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release** inside the OpenPlanner bridge's folder, two modules (traffic_light_selector and system_monitor) doesn't build.

**Comment by MarioAlmelaUMH** [comment]
Ok, I've figured it out. I updated the autoware.repos file present in the bridge with the autoware.repos file present in regular Autoware. The versions of the repositories were different, and on update, the bridge built normally, just like regular Autoware. Thank you anyway for your help.

**Comment by Eisoc** [comment]
Hello, I also use autoware-galactic branch, can you successfully engage at the end?
